export const FETCH_PRODUCT_DATA = "FETCH_PRODUCT_DATA";

export const FETCH_PRODUCT_DATA_SUCCESS = "FETCH_PRODUCT_DATA_SUCCESS";
export const FETCH_PRODUCT_DATA_ERROR = "FETCH_PRODUCT_DATA_ERROR";
export const UPDATE_COUNTER = "UPDATE_COUNTER" ;
export const REMOVE_PRODUCT = "REMOVE_PRODUCT"
